<style>
    .product-item-info {
        max-width: 100%;
        width: 20%;
        display: inline-block;
    }
</style>

<script type="text/javascript">
    require(["jquery"],function($) {
        $(document).ready(function() {
            $('#productsRangeForm').submit(function(event) {
                event.preventDefault();
                if( $(this).valid()){//!$(this).attr( "novalidate" )==='novalidate'){
                    var customurl = "<?php echo $this->getUrl().'productrangetab/customer/range/'?>";
                    $.ajax({
                        url: customurl,
                        type: 'POST',
                        dataType: 'json',
                        data: {
                            lowRange: $( "#lowRange" ).val(),
                            highRange: $( "#highRange" ).val(),
                            sortByPrice: $( "#sortByPrice" ).find(":selected").val(),
                        },
                        complete: function(response) {             
                            productList = response.responseJSON; 
                            $('#productList .product-items').empty();//delete previous products
                            productList.forEach(function(product, index, arr){
                                html='<div class="product-item-info" id="product-item-info_334" data-container="product-grid"><span class="product-image-container product-image-container-334" style="width: 240px;"><span class="product-image-wrapper" style="padding-bottom: 125%;">';
                                html=html+'<img class="product-image-photo" src="';
                                html=html+product.image+'" loading="lazy" width="240" height="300" alt="Lando Gym Jacket"></span>';
                                html=html+'</span><style>.product-item-name{font-size: 1.4rem;line-height: normal;letter-spacing: normal;margin-bottom: 16px;}.product-image-container-334 {width: 240px;}.product-image-container-334 span.product-image-wrapper {  padding-bottom: 125%; }</style>    </a>';
                                html=html+'<div class="product details product-item-details"><strong class="product name product-item-name"><a class="product-item-link" href="';
                                html=html+product.url+'">';
                                html=html+product.name+'</a></strong><div class="price-box price-final_price" data-role="priceBox" data-product-id="'+product.entity_id+'" data-price-box="product-id-334"><span class="normal-price">';
                                html=html+'<span class="price-container price-final_price tax weee"><span id="product-price-334" data-price-amount="99" data-price-type="finalPrice" class="price-wrapper "><span class="price">';
                                html=html+'$'+product.final_price+'</span></span></span></span></div></div></div>'
                                $('#productList .product-items').append(html);
                                console.log(html);  
                            });
                            
                        },
                        error: function (xhr, status, errorThrown) {
                            console.log('Error happens. Try again.');
                        }
                    });
                }
            });
        });
    });
</script>


<form class="form" id="productsRangeForm" method="post" data-mage-init='{"validation":{"rules": {"field-4": {"required":true}}}}'>
    <fieldset class="fieldset">
        <div class="field name required">
            <label class="label" for="lowRange"><span>Low Range</span></label>
            <div class="control">
                <input name="lowRange" id="lowRange" title="Low Range" value=""  class="input-text" type="number" data-validate='{"required-number":true, "validate-not-negative-number": true}'/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="highRange"><span>High Range</span></label>
            <div class="control">
                <input name="highRange" id="highRange" title="High Range" value="" class="input-text" type="number" data-validate='{"required-number":true, "greater-than-equals-to": "#lowRange"}'/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="field-3"><span>Sort By Price</span></label>
            <field name="sortByPrice" id="sortByPrice" formElement="select">
                <formElements>
                    <select>
                        <settings>
                            <options>
                                <option name="1" xsi:type="array">
                                    <item name="value">1</item>
                                    <item name="label" xsi:type="string">Ascending</item>
                                </option>
                                <option name="2" xsi:type="array">
                                    <item name="value">2</item>
                                    <item name="label" xsi:type="string">Descending</item>
                                </option>
                            </options>
                            <caption>-- Please Select --</caption>
                        </settings>
                    </select>
                </formElements>
            </field>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>


<div id="productList">
    <div class="products wrapper grid products-grid">
        <ol class="products list items product-items">
        </ol>
    </div>
</div>
