<style>
    .product-item-info {
        max-width: 100%;
        width: 20%;
        display: inline-block;

    }
    .product-item-name{
        font-size: 1.4rem;
        line-height: normal;
        letter-spacing: normal;
        margin-bottom: 5px;
    }
    .product-item-name a.product-item-link{
        font-weight:bold;
    }
    .product-image-container-334 {
        width: 240px;
    }
    .product-image-container-334 span.product-image-wrapper {  
        padding-bottom: 125%; 
    }
    .product-item-name.product-item-qty {
        margin-bottom: 15px;
    }
    .product-item-name.product-item-sku a.product-item-link{
        font-weight:500;
    }
</style>

<script>// <![CDATA[
    require([
        'jquery',
        'productRangeAjax'
    ], function ($, script) {});
    // ]]>
</script>


<form class="form" id="productsRangeForm" method="post" data-mage-init='{"validation":{"rules": {"field-4": {"required":true}}}}'>
    <fieldset class="fieldset">
        <input id="url" value="<?php echo $this->getUrl().'productrangetab/customer/range/'?>" type="hidden">
        <div class="field name required">
            <label class="label" for="lowRange"><span>Low Range</span></label>
            <div class="control">
                <input name="lowRange" id="lowRange" title="Low Range" value=""  class="input-text" type="number" data-validate='{"required-number":true, "validate-not-negative-number": true}'/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="highRange"><span>High Range</span></label>
            <div class="control">
                <input name="highRange" id="highRange" title="High Range" value="" class="input-text" type="number" data-validate='{"required-number":true, "greater-than-equals-to": "#lowRange", "validate-five-x":"#lowRange"}'/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="sortByPrice"><span>Sort By Price</span></label>
            <field name="sortByPrice" id="sortByPrice" formElement="select">
                <formElements>
                    <select>
                        <settings>
                            <options>
                                <option name="1" xsi:type="array">
                                    <item name="value">1</item>
                                    <item name="label" xsi:type="string">Ascending</item>
                                </option>
                                <option name="2" xsi:type="array">
                                    <item name="value">2</item>
                                    <item name="label" xsi:type="string">Descending</item>
                                </option>
                            </options>
                            <caption>-- Please Select --</caption>
                        </settings>
                    </select>
                </formElements>
            </field>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>


<div id="productList">
    <div class="products wrapper grid products-grid">
        <ol class="products list items product-items">
        </ol>
    </div>
</div>
